[notebook]
dir = "~/pkm"

# NOTE SETTINGS
[note]

# Language used when writing notes.
# This is used to generate slugs or with date formats.
language = "en"

# The default title used for new note, if no `--title` flag is provided.
default-title = "Untitled"

# Template used to generate a note's filename, without extension.
filename = "{{id}}"

# The file extension used for the notes.
extension = "md"

# Template used to generate a note's content.
# If not an absolute path, it is relative to .zk/templates/
template = "default.md"

# Configure random ID generation.

id-charset = "hex"
id-length = 8
id-case = "lower"


# EXTRA VARIABLES
[extra]
author = "Tanmay"


# GROUP OVERRIDES
[group.effort]
# Directories listed here will automatically use this group when creating notes.
paths = ["efforts"]


[group.meeting]
paths = ["meetings"]

[group.meeting.note]
filename = "{{slug title}}"
extension = "md"
template = "meeting.md"

[group.effort.note]
filename = "{{slug title}}"
extension = "md"
template = "effort.md"

[group.daily]
# Directories listed here will automatically use this group when creating notes.
paths = ["journal/daily"]

[group.daily.note]
# %Y-%m-%d is actually the default format, so you could use {{format-date now}} instead.
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"

[group.workspace]
paths = ["workspace/**"]

[group.workspace.note]
filename = "{{id}}"
template = "workspace.md"
id-charset = "alphanum"
id-length = 4
id-case = "lower"

# MARKDOWN SETTINGS
[format.markdown]
# Enable support for #hashtags
hashtags = true
# Enable support for :colon:separated:tags:
colon-tags = true


# EXTERNAL TOOLS
[tool]

# Default editor used to open notes.
editor = "nvim"

# Default shell used by aliases and commands.
shell = "zsh"

# Pager used to scroll through long output.
pager = "less -FIRX"

# Command used to preview a note during interactive fzf mode.
fzf-preview = "bat -p --color always {-1}"

# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two weeks'"

# COMMAND ALIASES
[alias]

daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/journal/daily"'

effort = 'zk new --no-input --title "$@" "$ZK_NOTEBOOK_DIR/efforts/" '

# Edit the last modified note.
edlast = "zk edit --limit 1 --sort modified- $@"

# Edit the notes selected interactively among the notes created the last two weeks.
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

# Show a random note.
lucky = "zk list --quiet --format full --sort random --limit 1"


# LSP (EDITOR INTEGRATION)
[lsp]

[lsp.diagnostics]
# Report titles of wiki-links as hints.
wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"
# Warn when notes link here without backlinks.
missing-backlink = { level = "warning", position = "bottom" }
