{ pkgs, userSettings, ... }:

let
  defaultTargetPath = userSettings.skill-publishing.target-path or "//depot/configs/users/$USER/_agents/skills";
  username = userSettings.username;
in
{
  home.packages = [
    (pkgs.writeScriptBin "skill-ctl" ''
      #!${pkgs.python3}/bin/python3
      import os
      import sys
      import subprocess
      import shutil
      import json
      import time
      import re
      
      USER = "${username}"
      DEFAULT_TARGET_PATH_TEMPLATE = "${defaultTargetPath}"
      SKILLS_DIR = os.path.expanduser("~/.gemini/skills")
      
      def get_citc_path(workspace, piper_path):
          # piper_path: //depot/foo/bar
          # We want /google/src/cloud/$USER/$WORKSPACE/foo/bar
          relative = piper_path.replace("//depot/", "")
          return f"/google/src/cloud/{USER}/{workspace}/{relative}"

      def create_workspace(name):
          ws_name = f"skill-pub-{name}-{int(time.time())}"
          print(f"Creating new CitC workspace: {ws_name}...")
          try:
              subprocess.run(["hg", "citc", ws_name], check=True, capture_output=True)
              return ws_name
          except subprocess.CalledProcessError as e:
              print(f"Error creating workspace: {e.stderr.decode()}")
              return None

      def update_configs(ws_root, skill_piper_path):
          agents_dir = os.path.join(ws_root, "configs/users", USER, "_agents")
          os.makedirs(agents_dir, exist_ok=True)
          
          # 1. Ensure gemini-extension.json exists
          ext_json_path = os.path.join(agents_dir, "gemini-extension.json")
          if not os.path.exists(ext_json_path):
              ext_data = {
                  "name": f"{USER}-personal-extension",
                  "version": "1.0.0",
                  "description": "Personal skills and configurations from Piper"
              }
              with open(ext_json_path, "w") as f:
                  json.dump(ext_data, f, indent=2)
              print(f"Created {ext_json_path}")

          # 2. Update skills.json
          skills_json_path = os.path.join(agents_dir, "skills.json")
          skill_rel_path = skill_piper_path.replace("//depot/", "")
          
          data = {"entries": []}
          if os.path.exists(skills_json_path):
              try:
                  with open(skills_json_path, "r") as f:
                      data = json.load(f)
              except:
                  pass
          
          if "entries" not in data:
              data["entries"] = []
              
          exists = False
          for entry in data["entries"]:
              if entry.get("path") == skill_rel_path:
                  exists = True
                  break
          
          if not exists:
              data["entries"].append({"path": skill_rel_path})
              with open(skills_json_path, "w") as f:
                  json.dump(data, f, indent=2)
              print(f"Updated {skills_json_path}")
              return True
          return False

      def publish_skill(name, target_piper_base=None):
          # 1. Verify local skill
          local_path = os.path.join(SKILLS_DIR, name)
          if not os.path.exists(local_path):
              print(f"Error: Local skill '{name}' not found in {SKILLS_DIR}.")
              return
          
          if not target_piper_base:
              target_piper_base = DEFAULT_TARGET_PATH_TEMPLATE.replace("$USER", USER)
          
          if target_piper_base.endswith("/"): target_piper_base = target_piper_base[:-1]
          target_piper_skill = f"{target_piper_base}/{name}"

          # 2. Create workspace
          workspace = create_workspace(name)
          if not workspace:
              return
          ws_root = f"/google/src/cloud/{USER}/{workspace}"
          target_citc_skill = get_citc_path(workspace, target_piper_skill)
          
          print(f"\nPublishing '{name}' to Piper...")
          print(f"Local path:  {local_path}")
          print(f"Piper path:  {target_piper_skill}")
          print(f"CitC path:   {target_citc_skill}")
          
          if os.path.exists(target_citc_skill):
              shutil.rmtree(target_citc_skill)
          
          os.makedirs(os.path.dirname(target_citc_skill), exist_ok=True)
          shutil.copytree(local_path, target_citc_skill)
          
          # 3. Update configs
          update_configs(ws_root, target_piper_skill)
          
          # 4. Hg operations
          try:
              print("\nAdding to source control...")
              subprocess.run(["hg", "add", "."], cwd=ws_root, check=True, capture_output=True)
              
              commit_msg = f"Add AI skill: {name}\n\nGenerated by skill-ctl."
              print("Creating local commit...")
              subprocess.run(["hg", "commit", "-m", commit_msg], cwd=ws_root, check=True)
              
              print("Uploading CL to Critique...")
              # hg upload will print the CL URL.
              result = subprocess.run(
                  ["hg", "upload", "."], 
                  cwd=ws_root, 
                  capture_output=True, 
                  text=True
              )
              
              # Extract CL URL from output
              cl_match = re.search(r"http://cl/\d+", result.stdout)
              if cl_match:
                  print(f"\n🚀 Skill successfully published! CL: {cl_match.group(0)}")
              else:
                  # Fallback: Try to find the CL via hg cls
                  try:
                      cls_out = subprocess.check_output(["hg", "cls"], cwd=ws_root, text=True)
                      cl_match = re.search(r"http://cl/\d+", cls_out)
                      if cl_match:
                          print(f"\n🚀 Skill successfully published! CL: {cl_match.group(0)}")
                      else:
                          print("\nSkill uploaded. Please check your CLs in workspace: " + workspace)
                  except:
                      print("\nSkill uploaded. Please check your CLs in workspace: " + workspace)
              
              print("\nNote: The skill will be available in Jetski Web and Cider once the CL is submitted.")
              
          except subprocess.CalledProcessError as e:
              print(f"\nError during hg operations: {e.stderr.decode() if e.stderr else e}")

      def main():
          if len(sys.argv) < 3 or sys.argv[1] != "publish":
              print("Usage: skill-ctl publish <skill_name> [target_piper_path]")
              sys.exit(1)
              
          name = sys.argv[2]
          target = sys.argv[3] if len(sys.argv) > 3 else None
          publish_skill(name, target)

      if __name__ == "__main__":
          main()
    '')
  ];
}
